### ISSUE TITLE
json:apiで来るresponseをhttp-intercepterを作ってフォーマットする

### ISSUE THREAD

**Issue by kahirokunn** [ispec-inc/waynes-ec-front#54]
json:apiで来るresponseをhttp-intercepterでフォーマットする

詳しくはこの辺のやり取りをみてください
https://ispec.slack.com/archives/CH84422DA/p1563809125005100

フォーマット結果については特に指定がないけど、なんかAPI使う人が扱いやすいって思うような形式にしていただけたらと思ってます。

**Comment by harutaka814** [comment]
フォーマット機能は以下のブランチで対応しました。
https://github.com/ispec-inc/waynes-ec-front/pull/55
